apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: healthcare/patient-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/healthcare-patient"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: healthcare-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: patient-uploads
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: patient-uploads
          persistentVolumeClaim:
            claimName: patient-uploads-pvc
